from __future__ import annotations

import uuid
from typing import Any

from claude_agent_sdk import ToolAnnotations, create_sdk_mcp_server, tool

from app.db.repositories.alert_repo import AlertRepo
from app.db.repositories.corridor_repo import CorridorRepo
from app.db.repositories.forecast_repo import ForecastRepo
from app.db.repositories.municipality_repo import MunicipalityRepo
from app.db.repositories.rerouting_plan_repo import ReroutingPlanRepo
from app.db.session import AsyncSessionLocal


def _severity(probability: float) -> str:
    if probability >= 0.85:
        return "HIGH"
    if probability >= 0.70:
        return "MEDIUM"
    return "LOW"


@tool(
    "get_active_alerts",
    "Returns all currently active alerts generated by the system. An alert is created when "
    "a corridor's closure probability exceeds the risk threshold (65%). Each alert includes "
    "the corridor name, probability, forecast horizon, and severity level. Call this first "
    "when the user asks about current alerts, active warnings, or what is happening right now.",
    {},
    annotations=ToolAnnotations(readOnlyHint=True, openWorldHint=False),
)
async def get_active_alerts(args: dict[str, Any]) -> dict[str, Any]:
    try:
        async with AsyncSessionLocal() as session:
            alerts = await AlertRepo(session).list_active(is_demo=False)
            if not alerts:
                return {"content": [{"type": "text", "text": "No active alerts at this time."}]}

            corridors = await CorridorRepo(session).list_all(is_demo=False)
            corridor_map = {c.id: c.name for c in corridors}

        lines = [f"**Active alerts ({len(alerts)}):**\n"]
        for a in sorted(alerts, key=lambda x: x.probability, reverse=True):
            name = corridor_map.get(a.corridor_id, str(a.corridor_id))
            lines.append(
                f"[{_severity(a.probability)}] **{name}**\n"
                f"  Probability: {int(a.probability * 100)}% | "
                f"Horizon: {a.horizon_hours}h | "
                f"Generated: {a.generated_at.strftime('%Y-%m-%d %H:%M UTC')}"
            )

        return {"content": [{"type": "text", "text": "\n\n".join(lines)}]}

    except Exception as e:
        return {
            "content": [{"type": "text", "text": f"Error fetching alerts: {e}"}],
            "is_error": True,
        }


@tool(
    "get_corridor_risks",
    "Returns road corridors in Ecuador at risk of closure for a given forecast horizon "
    "(24, 48, or 72 hours). Includes corridor name, closure probability, and population "
    "impacted. Use this when the user asks about road risk levels, which corridors are "
    "dangerous, or risk at a specific time horizon. Also returns the corridor_id (UUID) "
    "needed to call get_rerouting_plan.",
    {
        "type": "object",
        "properties": {
            "horizon_hours": {
                "type": "integer",
                "enum": [24, 48, 72],
                "description": "Forecast horizon in hours.",
            },
            "min_probability": {
                "type": "number",
                "minimum": 0.0,
                "maximum": 1.0,
                "description": "Minimum closure probability to include. Defaults to 0.5.",
            },
        },
        "required": ["horizon_hours"],
    },
    annotations=ToolAnnotations(readOnlyHint=True, openWorldHint=False),
)
async def get_corridor_risks(args: dict[str, Any]) -> dict[str, Any]:
    horizon = args["horizon_hours"]
    min_prob = args.get("min_probability", 0.5)

    try:
        async with AsyncSessionLocal() as session:
            forecasts = await ForecastRepo(session).list_latest_all(
                horizon_hours=horizon,
                is_demo=False,
            )
            corridors = {c.id: c for c in await CorridorRepo(session).list_all(is_demo=False)}

        filtered = sorted(
            [f for f in forecasts if f.probability >= min_prob],
            key=lambda x: x.probability,
            reverse=True,
        )

        if not filtered:
            return {
                "content": [
                    {
                        "type": "text",
                        "text": f"No corridors with closure probability ≥ {int(min_prob * 100)}% at {horizon}h horizon.",
                    }
                ]
            }

        lines = [f"**Corridor risks — {horizon}h horizon (≥{int(min_prob * 100)}%):**\n"]
        for f in filtered:
            corridor = corridors.get(f.corridor_id)
            name = corridor.name if corridor else str(f.corridor_id)
            population = f"{corridor.population_impact:,}" if corridor else "N/A"
            lines.append(
                f"• **{name}** — {int(f.probability * 100)}% closure risk\n"
                f"  Population impacted: {population} | corridor_id: `{f.corridor_id}`"
            )

        return {"content": [{"type": "text", "text": "\n\n".join(lines)}]}

    except Exception as e:
        return {
            "content": [{"type": "text", "text": f"Error fetching corridor risks: {e}"}],
            "is_error": True,
        }


@tool(
    "get_rerouting_plan",
    "Returns the pre-computed alternative routing plan for a specific corridor at risk of "
    "closure. Includes alternative route description, extra distance in km, extra travel "
    "time in minutes, and road notes. Use this when the user asks for detours, alternative "
    "routes, or how to bypass a specific corridor. Requires the corridor_id UUID from "
    "get_corridor_risks or get_active_alerts.",
    {"corridor_id": str},
    annotations=ToolAnnotations(readOnlyHint=True, openWorldHint=False),
)
async def get_rerouting_plan(args: dict[str, Any]) -> dict[str, Any]:
    corridor_id_str = args["corridor_id"]

    try:
        corridor_uuid = uuid.UUID(corridor_id_str)
    except ValueError:
        return {
            "content": [
                {
                    "type": "text",
                    "text": f"Invalid corridor_id format: '{corridor_id_str}'. Must be a UUID from get_corridor_risks.",
                }
            ],
            "is_error": True,
        }

    try:
        async with AsyncSessionLocal() as session:
            corridor = await CorridorRepo(session).get_by_id(corridor_uuid)
            plan = await ReroutingPlanRepo(session).get_by_corridor(corridor_uuid)

        if not plan:
            name = corridor.name if corridor else corridor_id_str
            return {
                "content": [
                    {
                        "type": "text",
                        "text": f"No rerouting plan found for corridor '{name}'. The pipeline may not have computed it yet.",
                    }
                ],
                "is_error": True,
            }

        corridor_name = corridor.name if corridor else corridor_id_str
        extra_hours = round(plan.duration_minutes / 60, 1)

        text = (
            f"**Rerouting plan — {corridor_name}:**\n"
            f"Route: {plan.via_description or 'See geometry'}\n"
            f"Extra distance: +{plan.distance_km:.1f} km | Extra time: +{extra_hours}h ({plan.duration_minutes:.0f} min)\n"
            f"Computed: {plan.computed_at.strftime('%Y-%m-%d %H:%M UTC')}"
        )

        return {"content": [{"type": "text", "text": text}]}

    except Exception as e:
        return {
            "content": [{"type": "text", "text": f"Error fetching rerouting plan: {e}"}],
            "is_error": True,
        }


@tool(
    "get_health_risk",
    "Returns municipalities with their historical epidemiological profile from PAHO/SIVIGILA "
    "(diseases prevalent during El Niño events). Also flags which corridors are currently "
    "at alert level so the user can understand which municipalities risk isolation. Use this "
    "when the user asks about health impact, epidemic risk, disease outbreaks, or medical "
    "supply pre-positioning.",
    {
        "type": "object",
        "properties": {
            "min_probability": {
                "type": "number",
                "minimum": 0.0,
                "maximum": 1.0,
                "description": "Only include municipalities whose access corridor has an active alert above this probability. Defaults to 0.0 (show all).",
            }
        },
        "required": [],
    },
    annotations=ToolAnnotations(readOnlyHint=True, openWorldHint=False),
)
async def get_health_risk(args: dict[str, Any]) -> dict[str, Any]:
    min_prob = args.get("min_probability", 0.0)

    try:
        async with AsyncSessionLocal() as session:
            municipalities = await MunicipalityRepo(session).list_all()
            active_alerts = await AlertRepo(session).list_active(is_demo=False)
            corridors = {c.id: c for c in await CorridorRepo(session).list_all(is_demo=False)}

        at_risk_corridors = {
            a.corridor_id: a.probability
            for a in active_alerts
            if a.probability >= min_prob
        }

        if not municipalities:
            return {
                "content": [
                    {
                        "type": "text",
                        "text": "No municipality data available. The seed pipeline may not have run yet.",
                    }
                ]
            }

        lines = ["**Municipality health profiles:**\n"]
        for m in municipalities:
            profile = m.epi_profile or {}
            diseases = list(profile.keys()) if profile else []
            epi_summary = ", ".join(diseases) if diseases else "No historical data"
            lines.append(
                f"**{m.name}** ({m.country})\n"
                f"  Historical El Niño diseases: {epi_summary}"
            )

        if at_risk_corridors:
            lines.append("\n**Corridors currently at alert level (potential isolation risk):**")
            for corridor_id, prob in sorted(at_risk_corridors.items(), key=lambda x: x[1], reverse=True):
                corridor = corridors.get(corridor_id)
                name = corridor.name if corridor else str(corridor_id)
                lines.append(f"  • {name} — {int(prob * 100)}% [{_severity(prob)}]")
        else:
            lines.append("\nNo corridors currently at alert level.")

        return {"content": [{"type": "text", "text": "\n\n".join(lines)}]}

    except Exception as e:
        return {
            "content": [{"type": "text", "text": f"Error fetching health risk data: {e}"}],
            "is_error": True,
        }


hermes_server = create_sdk_mcp_server(
    name="hermes",
    version="1.0.0",
    tools=[get_active_alerts, get_corridor_risks, get_rerouting_plan, get_health_risk],
)
